
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: Taiki
      POSTGRES_PASSWORD: gres06723
      POSTGRES_DB: safedb
    volumes:
     - pgdata:/var/lib/postgresql/data
  
  backend:
    build: ./server
    ports:
     - "3001:3001"
    depends_on:
     - db
    volumes:
     - ./server:/app
    environment:
      DATABASE_URL: postgresql://Taiki:gres06723@db:5432/safedb
    working_dir: /app
    command: npm run dev

  frontend:
    build: ./client
    ports:
     - "5173:5173"
    depends_on:
     - backend
    volumes:
     - ./client:/app
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0 --port 5173

volumes:
  pgdata: